add_newline = false

format = """$directory$git_branch$time $character"""

[directory]
style = "fg:#00ffff"
format = "[[ $path ](fg:#59c6eb bg:#394260)]($style)"
truncate_to_repo = false
truncation_length = 3
read_only = 'ğŸ”’'
read_only_style = 'red'
truncation_symbol = 'â€¦/'

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
"~/projects/" = "î©¹ "
"~" = "î¬† "

[git_branch]
symbol = "ï˜"
style = "bg:#394260"
format = '[ ](bold green)[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#394260"
format = '[ ](bold green)[[ ïº $time ](fg:#adadad bg:#394260)]($style)'

[character]
success_symbol = '[âœ](bold green)'
error_symbol = '[âœ—](bold red)'
